### PR TITLE
Drop Test::More dependency from encoding fallback tests

### PR DESCRIPTION
**Pull request by mhasch**
As the Encode module comes as a dependency of recent versions of Test::More, the test strategy in t/man/no-encode.t would not be able to cover modern platforms, as it needs Encode not to be loaded initially.
One way to cope is to replace Test::More by Test, at the cost of a bit of readability, in this particular test script.

### CODE REVIEW

**Comment by rra** [comment]
Hm, where are you seeing Encode becoming a dependency of new versions of Test::More? I looked at Test-Simple 1.302164, and it doesn't seem to have an Encode dependency. I'm probably just missing something, and your diff looks like a good idea if I am, but I'd rather avoid having two different test drivers in play if I can.

**Comment by mhasch** [comment]
> Hm, where are you seeing Encode becoming a dependency of new versions of Test::More? I looked at Test-Simple 1.302164, and it doesn't seem to have an Encode dependency.

Dependencies on core modules can get somewhat tricky to spot. An easy check whether your platform is affected is this command line:
``
perl -MTest::More -e 'print "Encode is already loaded\n" if exists $INC{"Encode.pm"}'

**Comment by mhasch** [comment]
Oops, shouldn't have closed this.

**Comment by mhasch** [comment]
It just occured to me that it is easier to simulate Encode.pm not being present than to avoid it altogether, which was your test strategy anyway. I've created [a new pull request](https://github.com/rra/podlators/pull/9) doing just that and close this one, again.

**Pull request closed without merging**
