### PR TITLE
load PerlIO before trying to use its functions

### PR DESCRIPTION
**Pull request by haarg**

### CODE REVIEW

**Comment by rra** [comment]
Did you encounter a problem that is fixed by this PR? My understanding is that PerlIO is not a regular Perl module and there's no need to import it before using functions in the PerlIO namespace. I just looked at `PerlIO.pm` in Perl 5.38.2 and it appears that `require PerlIO;` would not do anything.

**Comment by haarg** [comment]
This fixes #25.

The constant `PerlIO::F_UTF8` is only available once `PerlIO.pm` is loaded.

**Comment by rra** [comment]
Oh! Doh. Yes, thank you.

**Comment by youpong** [comment]
The bug appears to have been fixed. Thank you, @haarg.

**Pull request merged**
